export type Mode='explore'|'explode'|'xray'|'aero'|'floor';
export type Settings={generation:'2026'|'2025';mode:Mode;steer:number;travel:number;ride:number;rake:number;speed:number;wingOpen:boolean;explode:number;bodywork:boolean;floor:boolean;wheels:boolean;suspension:boolean;wings:boolean;internals:boolean;removeWheel:boolean;lighting:'studio'|'daylight'|'technical';spin:boolean;quality:'auto'|'high'|'low';selected:string|null};
export const initial:Settings={generation:'2026',mode:'explore',steer:0,travel:0,ride:45,rake:0,speed:200,wingOpen:false,explode:65,bodywork:true,floor:true,wheels:true,suspension:true,wings:true,internals:false,removeWheel:false,lighting:'studio',spin:false,quality:'auto',selected:null};
export const components:Record<string,{name:string;category:string;description:string;detail:string;camera:string}>={
 frontwing:{name:'Front wing',category:'Aerodynamics',description:'The first loaded surface conditions the flow reaching the front tyres and floor while balancing rear downforce.',detail:'2026: the movable wing sections flatten in Straight Mode. The 2025 comparison keeps the front wing fixed. Profiles here are inferred, not team aero sections.',camera:'Front wing'},
 nose:{name:'Nose & front impact structure',category:'Structure',description:'A tapered impact structure extends forward of the survival cell and supports the front wing.',detail:'Its exterior must satisfy aerodynamic geometry rules; the internal crush structure is not represented.',camera:'Front'},
 halo:{name:'Halo',category:'Driver protection',description:'A three-point structure protects the cockpit opening. A front pillar and two rear attachments carry loads into the survival cell.',detail:'The structural titanium core wears a composite aerodynamic fairing. The model shows the exterior, not a load-certified structure.',camera:'Cockpit'},
 cockpit:{name:'Cockpit & controls',category:'Driver interface',description:'A reclined seat, six-point harness and compact removable steering wheel fit inside the survival cell.',detail:'Buttons, rotary controls, display and paddles are a generic layout. The steering animation couples the wheel to the front uprights.',camera:'Cockpit'},
 suspension:{name:'Suspension & steering',category:'Mechanics',description:'Upper and lower wishbones locate the upright. A separate steering link turns the front wheel; a diagonal rod transmits vertical loads inboard.',detail:'The display uses a generic double-wishbone layout. Small travel moves the linkage endpoints; it is not a validated kinematic or compliance model.',camera:'Suspension'},
 brakes:{name:'Carbon brake assembly',category:'Braking',description:'A ventilated carbon disc rotates with the wheel while a caliper attached to the upright clamps it. Ducts carry cooling air into the assembly.',detail:'Remove the near front wheel to expose the disc, caliper, hub and duct. Dimensions and cooling-hole layout are representative.',camera:'Brakes'},
 tyres:{name:'Tyres & 18-inch wheels',category:'Contact patch',description:'Low-profile slick tyres surround 457.2 mm nominal bead-seat diameter wheels. The sidewall, shoulder and tread have distinct shapes and roughness.',detail:'The 2026 comparison has narrower, smaller-diameter tyres and exposed spokes. 2025 shows wheel covers. Nominal tyre envelopes are reference estimates.',camera:'Brakes'},
 sidepods:{name:'Sidepods & cooling inlets',category:'Cooling / aerodynamics',description:'Inlets feed the heat exchangers while the undercut and descending upper surface guide external air toward the rear of the car.',detail:'Cooling volume, inlet shape and the rear bodywork taper are inferred. Lifting the bodywork exposes two angled radiator volumes.',camera:'Side'},
 floor:{name:'Floor & underbody',category:'Ground effect',description:'The floor shapes the passage between the car and the road. Lower pressure beneath the car contributes to downforce.',detail:'2025 illustrates larger venturi passages. The 2026 reference uses a shallower floor concept; neither is a validated legal aero surface or a proprietary floor scan.',camera:'Underfloor'},
 tunnels:{name:'Underfloor passages',category:'Ground effect',description:'Air accelerates through a narrowing passage before expanding toward the diffuser. Geometry, ride height and flow separation all matter.',detail:'The dedicated floor view isolates the actual modeled surface. Flow traces are explanatory paths, not a CFD result.',camera:'Underfloor'},
 diffuser:{name:'Diffuser',category:'Aerodynamics',description:'The rising rear underfloor expands the flow passage and helps recover pressure. Its interaction with the rest of the car affects extraction from the floor.',detail:'An expansion that is too aggressive can separate the flow. The surface and strakes are illustrative geometry, not a computed optimum.',camera:'Rear'},
 rearwing:{name:'Rear wing & moving elements',category:'Aerodynamics',description:'The inverted wing loads the rear axle. Reducing its incidence lowers rear downforce and aerodynamic drag.',detail:'2026 Straight Mode coordinates front and rear aero. Switch to 2025 to demonstrate rear-only DRS and its opening slot.',camera:'Rear wing'},
 beam:{name:'Beam wing — 2025',category:'Aerodynamics',description:'The low rear wing interacts with the diffuser exit and upper rear wing as part of the rear aerodynamic system.',detail:'Shown only on the 2025 comparison; the 2026 reference omits it.',camera:'Rear'},
 power:{name:'Power unit & transmission',category:'Internal packaging',description:'The engine sits behind the fuel cell, with the gearbox farther aft. Exhaust piping converges toward a rear outlet.',detail:'Only approximate external volumes are shown. The power unit, turbocharger location and gearbox are not proprietary CAD or a service schematic.',camera:'Rear three-quarter'},
 cooling:{name:'Radiators & cooling paths',category:'Internal packaging',description:'Angled heat exchangers occupy the sidepods. Inlet air passes through their cores and leaves through bodywork outlets.',detail:'The coloured lines indicate approximate coolant routing; they are not a circuit diagram. Real packaging differs between teams.',camera:'Top'},
 fuel:{name:'Fuel cell & energy store',category:'Internal packaging',description:'The protected fuel bladder sits behind the driver and ahead of the engine. An energy-store envelope sits low within the chassis region.',detail:'Location and size are indicative. No exact fuel capacity, battery topology or crash structure is asserted.',camera:'Top'},
 monocoque:{name:'Survival cell',category:'Structure',description:'A carbon-composite survival cell surrounds the driver and fuel bladder and provides attachment points for the front suspension.',detail:'The visible shell is a packaging reference. Laminate schedules, inserts, bulkheads and structural validation are not represented.',camera:'Side'},
 exhaust:{name:'Exhaust & rear impact structure',category:'Rear assembly',description:'The exhaust exits above the rear impact structure. A rain light sits at the rear of the car.',detail:'A heat-tinted metal finish distinguishes the pipe from the surrounding composite. Internal heat shielding is simplified.',camera:'Rear'}
};
export const cameras=['Front three-quarter','Rear three-quarter','Side','Front','Rear','Top','Underfloor','Cockpit','Front wing','Rear wing','Suspension','Brakes'];
export const sources=[
 {title:'FIA 2026 technical regulations — Issue 20, 5 August 2026',url:'https://www.fia.com/system/files/documents/fia_2026_f1_regulations_-_section_c_technical_-_iss_20_-_2026-08-05.pdf',note:'C2.3: dimensions. C3: bodywork and moving wing elements. C10–12: wheels, brakes and survival cell.'},
 {title:'FIA 2025 technical regulations — Issue 3',url:'https://www.fia.com/sites/default/files/documents/fia_2025_formula_1_technical_regulations_-_issue_03_-_2025-04-07.pdf',note:'Regulatory reference for the 2025 comparison.'},
 {title:'FIA 2026 concept render gallery',url:'https://www.fia.com/multimedia/image-gallery/2026-fia-formula-1-regulations-renders',note:'Visual proportion reference only. No FIA images or logos are redistributed.'},
 {title:'FIA Formula 1 regulations — 2026 and archive',url:'https://www.fia.com/regulation/category/110',note:'Primary regulatory source. Generation differences and dimensional envelopes; not a certification of this model.'},
 {title:'Pirelli — Formula 1 tyres',url:'https://www.pirelli.com/tyres/en-ww/motorsport/f1/tyres',note:'Tyre architecture and compound context. No Pirelli branding or texture is reproduced.'},
 {title:'Three.js documentation',url:'https://threejs.org/docs/',note:'Physical materials, environment reflections, camera and WebGL rendering. MIT-licensed library.'}
];
