import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {components,initial,type Settings} from './data';

type Vec=[number,number,number];
type Part={group:T.Group;id:string;category:string;offset:T.Vector3};
const V=(p:Vec)=>new T.Vector3(...p),lerp=T.MathUtils.lerp;
function surface(n:number,m:number,fn:(u:number,v:number)=>Vec,uvscale:[number,number]=[1,1]){const p:number[]=[],uv:number[]=[],idx:number[]=[];for(let i=0;i<=n;i++)for(let j=0;j<=m;j++){p.push(...fn(i/n,j/m));uv.push(i/n*uvscale[0],j/m*uvscale[1])}for(let i=0;i<n;i++)for(let j=0;j<m;j++){const a=i*(m+1)+j,b=a+m+1;idx.push(a,b,a+1,b,b+1,a+1)}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();return g}
// Profiles are original engineering estimates in metres, not FIA homologation surfaces.
function loft(rows:number[][],sides=64){const curves=[0,1,2,3,4].map(k=>new T.SplineCurve(rows.map((r,i)=>new T.Vector2(i/(rows.length-1),r[k]??0))));return surface((rows.length-1)*12,sides,(u,v)=>{const r=curves.map(c=>c.getPoint(u).y),a=v*Math.PI*2;return [r[0],r[1]+Math.sin(a)*r[2],(r[4]||0)+Math.cos(a)*r[3]]},[Math.abs(rows.at(-1)![0]-rows[0][0])*45,55])}
function wingGeometry(span:number,chord:number,sweep=0,camber=.065,dihedral=0){return surface(48,48,(u,v)=>{const z=(u-.5)*span,t=v<.5?v*2:(1-v)*2;const th=5*.10*(.2969*Math.sqrt(t)-.126*t-.3516*t*t+.2843*t**3-.1036*t**4);const center=-camber*Math.sin(Math.PI*t);return [chord*t+Math.abs(z)*sweep,chord*(center+(v<.5?th:-th))+dihedral*(2*z/span)**2,z]},[span*45,chord*90])}
function noiseTexture(kind:'carbon'|'rubber'|'plank'){const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d')!,d=ctx.createImageData(256,256);let seed=38291;const rnd=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296};for(let y=0;y<256;y++)for(let x=0;x<256;x++){const i=(y*256+x)*4;let r=0,g=0,b=0;if(kind==='carbon'){const a=Math.floor(x/16),b0=Math.floor(y/16),over=((a-b0)%4+4)%4<2;const thread=over?x%16:y%16,shine=Math.sin(thread/16*Math.PI);const n=rnd()*4;const c0=over?28:20;r=g=b=c0+shine*18+n;}else if(kind==='rubber'){r=g=b=83+rnd()*23+3*Math.sin(y*.6);}else{const n=rnd()*12+9*Math.sin(x*.4+Math.sin(y*.01));r=124+n;g=90+n*.7;b=53+n*.45}d.data[i]=r;d.data[i+1]=g;d.data[i+2]=b;d.data[i+3]=255}ctx.putImageData(d,0,0);const t=new T.CanvasTexture(c);t.wrapS=t.wrapT=T.RepeatWrapping;t.colorSpace=T.SRGBColorSpace;t.anisotropy=8;return t}
function labelTexture(text:string){const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d')!;x.fillStyle='#12181e';x.fillRect(0,0,512,256);x.fillStyle='#d7e7e1';x.font='bold 120px monospace';x.fillText(text,22,145);x.fillStyle='#ee492b';for(let i=0;i<13;i++)x.fillRect(24+i*36,205,22,10);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t}
function tyreMarkings(){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d')!;x.translate(256,256);x.strokeStyle='#d6bf8b';x.lineWidth=3;x.beginPath();x.arc(0,0,207,0,Math.PI*2);x.stroke();x.fillStyle='#a6a7a3';x.textAlign='center';x.textBaseline='middle';x.font='500 23px Arial';for(const [str,start] of [['S L I C K   /   1 8',-Math.PI*.5],['R E F E R E N C E',Math.PI*.5]] as [string,number][]){for(let i=0;i<str.length;i++){const a=start+(i-(str.length-1)/2)*.085;x.save();x.rotate(a);x.translate(0,-224);x.fillText(str[i],0,0);x.restore()}}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t}

export class Explorer{
 host:HTMLDivElement;renderer:T.WebGLRenderer;scene=new T.Scene();camera:T.PerspectiveCamera;controls:OrbitControls;root=new T.Group();parts:Part[]=[];meshes:T.Mesh[]=[];materials:T.MeshStandardMaterial[]=[];mat:Record<string,T.MeshPhysicalMaterial|T.MeshStandardMaterial>={};markTexture?:T.CanvasTexture;s:Settings={...initial};frontFlaps:T.Group[]=[];rearFlaps:T.Group[]=[];wheelPivots:{pivot:T.Group;wheel:T.Group;side:number;front:boolean;x:number;z:number;r:number}[]=[];links:{mesh:T.Mesh;a:Vec;b:Vec;side:number;tie:boolean;front:boolean;x:number;z:number}[]=[];steering?:T.Group;floorParts:Part[]=[];flows:{curve:T.CatmullRomCurve3;points:T.Points;line:T.Line;phase:number;floor:boolean}[]=[];flowRoot=new T.Group();ground:T.Mesh;grid:T.GridHelper;shadow:T.Mesh;key:T.DirectionalLight;fill:T.DirectionalLight;rim:T.DirectionalLight;environment:T.WebGLRenderTarget;clock={elapsedTime:0,last:performance.now(),getDelta(){const t=performance.now();const d=(t-this.last)/1000;this.last=t;this.elapsedTime+=Math.min(d,.04);return d}};frame=0;resize:ResizeObserver;ray=new T.Raycaster();pointer=new T.Vector2();targetCam:T.Vector3|null=null;targetLook:T.Vector3|null=null;lastTime=0;slow=0;renderCount=0;stopped=false;pointerDown:Vec=[0,0,0];select:(id:string)=>void;hover:(label:string)=>void;stats:(s:string)=>void;reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;qualityDpr=1.5;userActive=true;
 constructor(host:HTMLDivElement,select:(id:string)=>void,hover:(s:string)=>void,stats:(s:string)=>void){
 this.host=host;this.select=select;this.hover=hover;this.stats=stats;this.renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,host.clientWidth<700?1.4:1.8));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.12;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.setClearColor('#e7eaec');host.appendChild(this.renderer.domElement);this.renderer.domElement.setAttribute('aria-label','Rendered Formula reference car');
 this.camera=new T.PerspectiveCamera(32,1,.02,150);this.camera.position.set(-6.6,3.25,6.3);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.target.set(-.08,.34,0);this.controls.enableDamping=true;this.controls.dampingFactor=.07;this.controls.minDistance=.38;this.controls.maxDistance=17;this.controls.maxPolarAngle=Math.PI-.015;this.controls.minPolarAngle=.015;this.controls.rotateSpeed=.65;this.controls.zoomSpeed=.75;this.controls.addEventListener('start',()=>{this.targetCam=null;this.targetLook=null});
 const pmrem=new T.PMREMGenerator(this.renderer),envScene=new RoomEnvironment();this.environment=pmrem.fromScene(envScene,.035);this.scene.environment=this.environment.texture;this.scene.environmentIntensity=.85;envScene.dispose();pmrem.dispose();this.scene.background=new T.Color('#e7eaec');this.scene.fog=new T.Fog('#e7eaec',20,45);
 this.scene.add(new T.HemisphereLight('#f7fbff','#636d78',1.6));this.key=new T.DirectionalLight('#fff8ee',4);this.key.position.set(-3,6,4);this.key.castShadow=true;this.key.shadow.mapSize.set(2048,2048);Object.assign(this.key.shadow.camera,{left:-4,right:4,top:4,bottom:-4,near:.5,far:15});this.key.shadow.bias=-.0002;this.key.shadow.normalBias=.012;this.key.shadow.radius=4;this.scene.add(this.key);this.fill=new T.DirectionalLight('#dbe9ff',1.7);this.fill.position.set(1,4,-5);this.scene.add(this.fill);this.rim=new T.DirectionalLight('#ffffff',2.5);this.rim.position.set(5,3,1);this.scene.add(this.rim);
 this.ground=new T.Mesh(new T.PlaneGeometry(150,150),new T.MeshStandardMaterial({color:'#e3e7e9',roughness:.87,metalness:0}));this.ground.rotation.x=-Math.PI/2;this.ground.position.y=-.003;this.ground.receiveShadow=true;this.scene.add(this.ground);this.grid=new T.GridHelper(12,24,'#bfc9ce','#d2dadf');this.grid.position.y=-.001;this.grid.visible=false;this.scene.add(this.grid);
 // Soft contact patches are original radial opacity textures, not surface geometry.
 const c=document.createElement('canvas');c.width=c.height=128;const cx=c.getContext('2d')!,gr=cx.createRadialGradient(64,64,0,64,64,62);gr.addColorStop(0,'rgba(0,0,0,.22)');gr.addColorStop(.4,'rgba(0,0,0,.13)');gr.addColorStop(1,'rgba(0,0,0,0)');cx.fillStyle=gr;cx.fillRect(0,0,128,128);this.shadow=new T.Mesh(new T.PlaneGeometry(6,2.8),new T.MeshBasicMaterial({map:new T.CanvasTexture(c),transparent:true,depthWrite:false}));this.shadow.rotation.x=-Math.PI/2;this.shadow.position.set(0,.0005,0);this.scene.add(this.shadow);
 this.makeMaterials();this.scene.add(this.root,this.flowRoot);this.build();this.makeFlow();this.resize=new ResizeObserver(()=>this.resizeNow());this.resize.observe(host);this.resizeNow();this.view('Front three-quarter');host.addEventListener('pointerdown',this.onDown);host.addEventListener('pointerup',this.onUp);host.addEventListener('pointermove',this.onMove);host.addEventListener('pointerleave',this.onLeave);host.addEventListener('keydown',this.onKey);document.addEventListener('visibilitychange',this.onVisibility);this.renderer.domElement.addEventListener('webglcontextlost',this.onLost);this.loop();
 }
 makeMaterials(){const carbon=noiseTexture('carbon'),rubber=noiseTexture('rubber'),wood=noiseTexture('plank');const mat=(name:string,p:T.MeshPhysicalMaterialParameters)=>this.mat[name]=new T.MeshPhysicalMaterial({side:T.DoubleSide,...p});mat('carbon',{color:'#3d4245',map:carbon,roughness:.34,metalness:.22,clearcoat:.35,clearcoatRoughness:.3,bumpMap:carbon,bumpScale:.00022,anisotropy:.45});mat('matte',{color:'#171e22',map:carbon,roughness:.65,metalness:.12,bumpMap:carbon,bumpScale:.00025});mat('paint',{color:'#d9dfe2',roughness:.28,metalness:.68,clearcoat:1,clearcoatRoughness:.19});mat('red',{color:'#e33f24',roughness:.3,metalness:.2,clearcoat:.9});mat('rubber',{color:'#24292b',roughness:.87,roughnessMap:rubber,bumpMap:rubber,bumpScale:.0005});mat('metal',{color:'#aab5bf',roughness:.3,metalness:.92});mat('rim',{color:'#263039',roughness:.26,metalness:.9});mat('disc',{color:'#33363a',map:rubber,roughness:.8,metalness:.15});mat('caliper',{color:'#847765',roughness:.36,metalness:.8});mat('black',{color:'#090e12',roughness:.9});mat('wood',{map:wood,color:'#baa085',roughness:.78});mat('seat',{color:'#252d34',roughness:1,bumpMap:rubber,bumpScale:.001});mat('engine',{color:'#aab5bd',roughness:.38,metalness:.8});mat('copper',{color:'#c78341',roughness:.29,metalness:.8});mat('fuel',{color:'#ba944a',roughness:.65});mat('battery',{color:'#426e83',roughness:.4,metalness:.4});mat('cool',{color:'#498ca3',roughness:.4,metalness:.4});mat('exhaust',{color:'#938374',roughness:.31,metalness:1});mat('light',{color:'#e6331e',emissive:'#ff2200',emissiveIntensity:2,roughness:.2});}
 group(id:string,category:string,offset:Vec=[0,0,0]){const g=new T.Group();g.name=id;this.root.add(g);this.parts.push({group:g,id,category,offset:V(offset)});return g}
 mesh(g:T.Object3D,geo:T.BufferGeometry,material:string,id?:string,pos:Vec=[0,0,0]){const m=new T.Mesh(geo,this.mat[material].clone());m.position.set(...pos);m.castShadow=true;m.receiveShadow=true;let p:T.Object3D|null=g;while(p&&!p.name)p=p.parent;m.userData.id=id||p?.name||'monocoque';m.userData.baseColor=(m.material as T.MeshStandardMaterial).color.clone();m.userData.originalMaterial=m.material;g.add(m);this.meshes.push(m);this.materials.push(m.material as T.MeshStandardMaterial);return m}
 box(g:T.Object3D,dim:Vec,pos:Vec,mat:string,id?:string,r=.008){return this.mesh(g,new RoundedBoxGeometry(...dim,2,r),mat,id,pos)}
 rod(g:T.Object3D,a:Vec,b:Vec,r:number,mat:string,id?:string,flat=1){const m=this.mesh(g,new T.CylinderGeometry(r,r,1,10),mat,id);this.positionRod(m,V(a),V(b),flat);return m}
 positionRod(m:T.Mesh,a:T.Vector3,b:T.Vector3,flat=1){m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),b.clone().sub(a).normalize());m.scale.set(flat,a.distanceTo(b),1)}
 tube(g:T.Object3D,points:Vec[],r:number,mat:string,id?:string,closed=false){return this.mesh(g,new T.TubeGeometry(new T.CatmullRomCurve3(points.map(V),closed,'centripetal'),points.length*12,r,10,closed),mat,id)}
 cylinder(g:T.Object3D,r:number,depth:number,pos:Vec,mat:string,id?:string){const m=this.mesh(g,new T.CylinderGeometry(r,r,depth,48),mat,id,pos);m.rotation.x=Math.PI/2;return m}
 ring(g:T.Object3D,inner:number,outer:number,pos:Vec,mat:string,id?:string){return this.mesh(g,new T.RingGeometry(inner,outer,96),mat,id,pos)}
 build(){this.disposeCar();this.frontFlaps=[];this.rearFlaps=[];this.wheelPivots=[];this.links=[];const old=this.s.generation==='2025',ax=old?1.8:1.7,width=old?1: .95;const fw=this.group('frontwing','wings',[-.55,.14,0]);const wingSpan=old?1.94:1.79;
 // Multiple closed, curved aerofoil sections, with separate hinges.
 const n=old?4:3;for(let i=0;i<n;i++){const z=0,x=-ax-.99+i*.115,y=.13+i*.049,span=wingSpan-i*.012;const flap=new T.Group();flap.position.set(x,y,z);fw.add(flap);const m=this.mesh(flap,wingGeometry(span,i===0?.245:.172,.07,.065,.07),'carbon','frontwing',[-.13,0,0]);m.rotation.z=.08+i*.1;if(i>0)this.frontFlaps.push(flap);if(i===n-1){const stripe=this.mesh(flap,wingGeometry(span,.018,.07,0,.07),'red','frontwing',[-.009,.004,0]);stripe.rotation.z=m.rotation.z}}
 for(const sign of [-1,1]){const shape=new T.Shape();shape.moveTo(-ax-1.08,.08);shape.quadraticCurveTo(-ax-1.08,.13,-ax-.94,.27);shape.quadraticCurveTo(-ax-.84,.32,-ax-.64,.31);shape.lineTo(-ax-.47,.27);shape.lineTo(-ax-.43,.095);shape.closePath();this.mesh(fw,new T.ExtrudeGeometry(shape,{depth:.012,steps:1,bevelEnabled:true,bevelThickness:.003,bevelSize:.004,bevelSegments:3,curveSegments:16}),'paint','frontwing',[0,0,sign*wingSpan/2-.006]);this.tube(fw,[[-ax-.9,.19,sign*.5],[-ax-.81,.28,sign*.51],[-ax-.69,.35,sign*.52]],.006,'metal','frontwing');}
 const nose=this.group('nose','bodywork',[-.37,.26,0]);this.mesh(nose,loft([[-ax-1.04,.265,.025,.045],[-ax-.88,.29,.053,.083],[-ax-.54,.34,.08,.105],[-ax-.11,.415,.105,.13],[-ax+.33,.465,.12,.18],[-.91,.455,.125,.24]]),'paint','nose');this.tube(nose,[[-ax-.94,.320,0],[-ax-.78,.361,0],[-ax-.53,.426,0],[-ax-.15,.514,0],[-ax+.20,.573,0],[-.97,.585,0]],.007,'red','nose');
 const tub=this.group('monocoque','bodywork',[0,.48,0]);this.mesh(tub,loft([[-1.35,.325,.13,.17],[-1.04,.355,.19,.255],[-.77,.36,.205,.3],[-.65,.35,.21,.32]]),'paint','monocoque');
 // The opening is built into the shell; there is no solid shape across the seat.
 for(const sign of [-1,1]){this.mesh(tub,loft([[-.7,.35,.225,.078,sign*.26],[-.42,.365,.237,.06,sign*.302],[-.02,.382,.25,.07,sign*.307],[.37,.385,.255,.095,sign*.28],[.61,.36,.25,.16,sign*.2]]),'paint','monocoque');this.tube(tub,[[-.72,.56,sign*.25],[-.38,.603,sign*.29],[.06,.634,sign*.30],[.42,.64,sign*.255]],.014,'carbon','cockpit')}
 this.box(tub,[1.2,.085,.53],[-.06,.17,0],'carbon','monocoque',.024);this.mesh(tub,loft([[.37,.36,.235,.28],[.58,.39,.25,.29],[.82,.40,.24,.26]]),'carbon','monocoque');
 const cockpit=this.group('cockpit','cockpit',[0,.12,0]);const seat=this.box(cockpit,[.12,.5,.34],[.27,.44,0],'seat','cockpit',.05);seat.rotation.z=.36;this.box(cockpit,[.51,.09,.30],[-.06,.235,0],'seat','cockpit',.035);this.box(cockpit,[.67,.055,.25],[-.48,.29,0],'seat','cockpit',.025).rotation.z=-.12;
 for(const sign of [-1,1]){this.box(cockpit,[.37,.105,.085],[.20,.69,sign*.19],'seat','cockpit',.035);this.tube(cockpit,[[.30,.66,sign*.11],[.23,.48,sign*.10],[.04,.30,sign*.07]],.025,'red','cockpit');this.tube(cockpit,[[.27,.30,sign*.20],[.03,.30,sign*.06]],.021,'red','cockpit');this.tube(cockpit,[[-.16,.25,sign*.12],[.03,.30,sign*.04]],.018,'red','cockpit')}
 this.cylinder(cockpit,.042,.018,[.02,.32,0],'metal','cockpit').rotation.x=0;
 // Steering wheel lies in the y-z plane, with a longitudinal column.
 this.rod(cockpit,[-1.03,.43,0],[-.54,.53,0],.014,'metal','cockpit');const sw=new T.Group();sw.position.set(-.53,.53,0);sw.rotation.z=-.17;cockpit.add(sw);this.steering=sw;const plate=this.box(sw,[.023,.175,.272],[0,0,0],'carbon','cockpit',.027);for(const sign of [-1,1]){this.tube(sw,[[0,.078,sign*.112],[.007,.065,sign*.149],[.008,0,sign*.158],[.006,-.063,sign*.133],[0,-.074,sign*.099]],.023,'seat','cockpit');this.box(sw,[.008,.11,.07],[-.029,-.005,sign*.10],'metal','cockpit',.016)}
 const screen=this.box(sw,[.004,.066,.122],[.015,.037,0],'black','cockpit',.003);(screen as T.Mesh).material=new T.MeshBasicMaterial({map:labelTexture('N  00')});screen.userData.baseColor=new T.Color('#ffffff');this.box(sw,[.004,.025,.12],[.017,-.052,0],'black','cockpit',.003);
 for(let i=0;i<10;i++){const side=i<5?-1:1,j=i%5;const b=this.mesh(sw,new T.CylinderGeometry(.009,.009,.006,16),j%3===0?'red':j%3===1?'cool':'metal','cockpit',[.019,.059-j*.028,side*(.092+(j===2?.023:0))]);b.rotation.z=Math.PI/2}for(let i=0;i<3;i++){const knob=this.mesh(sw,new T.CylinderGeometry(.017,.017,.01,12),i===1?'red':'metal','cockpit',[.02,-.015,(i-1)*.045]);knob.rotation.z=Math.PI/2;this.box(sw,[.005,.013,.004],[.028,-.009,(i-1)*.045],'black','cockpit',.001)}for(let i=0;i<11;i++)this.box(sw,[.006,.006,.006],[.015,.094,(i-5)*.012],i<5?'cool':'red','cockpit',.002);
 const halo=this.group('halo','bodywork',[0,.57,0]);this.tube(halo,[[.39,.71,-.29],[.28,.86,-.30],[-.12,.89,-.255],[-.59,.84,-.13],[-.75,.82,0],[-.59,.84,.13],[-.12,.89,.255],[.28,.86,.30],[.39,.71,.29]],.028,'paint','halo');this.tube(halo,[[-.75,.82,0],[-.755,.69,0],[-.69,.575,0]],.023,'carbon','halo');for(const sign of [-1,1]){this.box(halo,[.095,.037,.09],[.385,.70,sign*.29],'carbon','halo',.012);this.box(tub,[.067,.016,.024],[-.22,.65,sign*.31],'metal','cockpit',.002)}
 // Separate sidepods with open, black throat inserts and descending rear decks.
 for(const sign of [-1,1]){const pod=this.group('sidepods','bodywork',[.05,.40,sign*.34]);const profiles=[[-.63,.545,.378,.32,.73],[-.4,.574,.322,.30,.77],[.03,.52,.264,.30,.77],[.49,.386,.213,.29,.68],[.94,.285,.192,.24,.47],[1.29,.224,.182,.21,.29]];const curves=[0,1,2,3,4].map(k=>new T.SplineCurve(profiles.map((r,i)=>new T.Vector2(i/(profiles.length-1),r[k]))));this.mesh(pod,surface(90,64,(u,v)=>{const r=curves.map(c=>c.getPoint(u).y),a=v*Math.PI*2,sy=Math.sin(a),sz=Math.cos(a);const y=(r[1]+r[2])/2+Math.sign(sy)*Math.abs(sy)**.7*(r[1]-r[2])/2,z=sign*((r[3]+r[4])/2+Math.sign(sz)*Math.abs(sz)**.65*(r[4]-r[3])/2);return[r[0],y,z]},[86,34]),'paint','sidepods');
const opening:Vec[]=[];for(let i=0;i<=48;i++){const a=i/48*Math.PI*2;opening.push([-.64,.462+Math.sign(Math.sin(a))*Math.abs(Math.sin(a))**.6*.061,sign*(.525+Math.sign(Math.cos(a))*Math.abs(Math.cos(a))**.65*.169)])}this.tube(pod,opening,.007,'carbon','sidepods');this.mesh(pod,surface(48,5,(u,v)=>{const a=u*Math.PI*2;return[-.634,.462+Math.sign(Math.sin(a))*Math.abs(Math.sin(a))**.6*.059*v,sign*(.525+Math.sign(Math.cos(a))*Math.abs(Math.cos(a))**.65*.168*v)]}), 'black','sidepods');
this.tube(pod,[[-.49,.54,sign*.74],[-.09,.50,sign*.76],[.45,.358,sign*.685],[.90,.265,sign*.49]],.007,'red','sidepods');
 // Cooling louvres on the sloping top face.
 for(let i=0;i<10;i++){const x=.03+i*.047,y=.526-i*.015;this.box(pod,[.013,.006,.115],[x,y,sign*.48],'black','sidepods',.003).rotation.z=-.3;}
 this.tube(pod,[[-.46,.53,sign*.42],[-.45,.69,sign*.52],[-.40,.70,sign*.61]],.012,'carbon','sidepods');this.box(pod,[.17,.065,.11],[-.4,.72,sign*.62],'paint','sidepods',.028);this.box(pod,[.006,.043,.080],[-.305,.72,sign*.62],'metal','sidepods',.012);
 const cool=this.group('cooling','internals',[0,.2,sign*.24]);const rad=this.box(cool,[.75,.065,.28],[.04,.39,sign*.47],'engine','cooling',.015);rad.rotation.z=-.21;rad.rotation.x=sign*.55;for(let i=0;i<23;i++){const x=-.30+i*.029;this.box(cool,[.007,.057,.255],[x,.4-(x+.05)*.2,sign*.47],'rim','cooling',.001).rotation.x=sign*.55}this.tube(cool,[[-.25,.42,sign*.40],[.15,.32,sign*.34],[.49,.29,sign*.22],[.85,.39,sign*.20]],.019,'cool','cooling');this.tube(cool,[[.89,.24,sign*.19],[.46,.21,sign*.34],[-.12,.28,sign*.45]],.015,'copper','cooling');}
 const cover=this.group('power','bodywork',[.1,.63,0]);this.mesh(cover,loft([[.43,.70,.225,.16],[.64,.64,.27,.21],[.93,.49,.245,.23],[1.27,.345,.115,.17],[1.61,.28,.055,.075],[1.86,.285,.035,.045]],64),'paint','power');this.mesh(cover,loft([[.40,.925,.09,.105],[.49,.967,.105,.113],[.63,.951,.101,.103],[.88,.84,.067,.059]],48),'carbon','power');this.mesh(cover,loft([[.387,.969,.064,.075],[.414,.969,.064,.075]],48),'black','power');this.mesh(cover,loft([[.43,.965,.007,.078],[.62,.997,.007,.065],[.82,.91,.007,.027]],24),'red','power');
 // Dorsal fin, closing down toward the tail.
 this.mesh(cover,surface(32,1,(u,v)=>{const x=.7+u*1.1,top=.91-u*.59,bottom=.64-u*.36;return[x,lerp(bottom,top,v),0]}),'carbon','power');this.box(cover,[.16,.04,.32],[.5,1.06,0],'black','power',.016);this.box(cover,[.048,.042,.033],[.44,1.063,.135],'metal','power',.009);
 const fuel=this.group('fuel','internals',[0,.16,0]);this.box(fuel,[.42,.37,.43],[.49,.34,0],'fuel','fuel',.046);this.box(fuel,[.44,.09,.33],[.22,.19,0],'battery','fuel',.018);
 const power=this.group('power','internals',[.19,.23,0]);this.box(power,[.66,.31,.38],[1.00,.30,0],'engine','power',.025);for(const sign of [-1,1]){const head=this.box(power,[.65,.14,.16],[.96,.48,sign*.15],'rim','power',.018);head.rotation.x=sign*.38;for(let i=0;i<7;i++)this.box(power,[.012,.04,.16],[.70+i*.09,.53,sign*.16],'metal','power',.002);for(let i=0;i<3;i++)this.tube(power,[[.76+i*.19,.34,sign*.22],[.78+i*.19,.28,sign*.31],[1.4,.32,sign*.19]],.027,'exhaust','exhaust')}
 this.box(power,[.61,.225,.23],[1.63,.285,0],'rim','power',.055);for(let i=0;i<6;i++)this.box(power,[.011,.24,.24],[1.4+i*.07,.29,0],'metal','power',.002);this.cylinder(power,.10,.10,[1.33,.48,0],'exhaust','exhaust');this.tube(power,[[1.35,.47,0],[1.58,.47,0],[1.90,.445,0],[2.14,.43,0]],.045,'exhaust','exhaust');this.mesh(power,new T.RingGeometry(.038,.046,48),'exhaust','exhaust',[2.14,.43,0]).rotation.y=Math.PI/2;this.mesh(power,new T.CircleGeometry(.038,48),'black','exhaust',[2.142,.43,0]).rotation.y=Math.PI/2;
 const crash=this.group('exhaust','structure',[.38,.1,0]);this.mesh(crash,loft([[1.55,.22,.095,.11],[1.82,.21,.067,.077],[2.08,.21,.042,.051]]),'carbon','exhaust');this.box(crash,[.021,.077,.093],[2.105,.22,0],'light','exhaust',.01);
 this.makeFloor(old,ax);
 const rw=this.group('rearwing','wings',[.53,.52,0]);const rearX=ax+.30,span=old?1.02:1.10;
 for(const sign of [-1,1]){this.tube(rw,[[ax-.18,.27,sign*.09],[ax-.22,.54,sign*.095],[ax-.17,.78,sign*.09],[ax-.03,.86,sign*.085]],.017,'carbon','rearwing');const ep=new T.Shape();ep.moveTo(rearX-.13,.80);ep.quadraticCurveTo(rearX-.16,.63,rearX+.08,.43);ep.lineTo(rearX+.32,.43);ep.lineTo(rearX+.42,.91);ep.quadraticCurveTo(rearX+.16,.94,rearX-.13,.80);this.mesh(rw,new T.ExtrudeGeometry(ep,{depth:.011,bevelEnabled:true,bevelThickness:.002,bevelSize:.003,bevelSegments:2,curveSegments:18}),'paint','rearwing',[0,0,sign*span/2-.006])}
 const main=this.mesh(rw,wingGeometry(span,.31,0,.095,.055),'carbon','rearwing',[rearX-.13,.80,0]);main.rotation.z=.15;
 const flap=new T.Group();flap.position.set(rearX+.30,.947,0);rw.add(flap);const movable=this.mesh(flap,wingGeometry(span-.032,old?.235:.22,0,.07,.015),'paint','rearwing',[-.235,-.066,0]);movable.rotation.z=.28;this.mesh(flap,wingGeometry(span-.035,.018,0,0,.014),'red','rearwing',[-.030,-.005,0]);this.rearFlaps.push(flap);
 if(!old){const second=new T.Group();second.position.set(rearX+.11,.875,0);rw.add(second);this.mesh(second,wingGeometry(span-.03,.16,0,.07,.02),'carbon','rearwing',[-.16,-.035,0]).rotation.z=.24;flap.add(second);second.position.set(-.19,-.07,0)}
 this.rod(rw,[rearX+.27,.875,0],[rearX+.30,.959,0],.008,'metal','rearwing');this.box(rw,[.10,.035,.043],[rearX+.28,.967,0],'carbon','rearwing',.008);
 if(old){const beam=this.group('beam','wings',[.40,.27,0]);for(let i=0;i<2;i++)this.mesh(beam,wingGeometry(.84,.16,0,.06,.07),'carbon','beam',[ax+.01+i*.11,.36+i*.08,0]).rotation.z=.22}
 for(const front of [true,false])for(const sign of [-1,1])this.makeWheel(front,sign,ax,width,old);
 // Small visible fasteners: instanced to retain close-up detail economically.
 const bolts=this.group('monocoque','bodywork',[0,.48,0]);const geo=new T.CylinderGeometry(.005,.005,.003,6);const fast=new T.InstancedMesh(geo,this.mat.metal,26);const dummy=new T.Object3D();let index=0;for(const sign of [-1,1])for(let i=0;i<13;i++){dummy.position.set(-.66+i*.1,.592,sign*.315);dummy.rotation.set(0,0,0);dummy.updateMatrix();fast.setMatrixAt(index++,dummy.matrix)}fast.userData.id='monocoque';bolts.add(fast);this.meshes.push(fast);
 // A driver silhouette is deliberately a packaging envelope, visible only in cutaway.
 const driver=this.group('cockpit','internals',[0,0,0]);const helmet=this.mesh(driver,new T.SphereGeometry(.105,32,24),'seat','cockpit',[.06,.72,0]);helmet.scale.set(.98,1.18,.85);this.box(driver,[.31,.22,.28],[.03,.45,0],'seat','cockpit',.08).rotation.z=.6;for(const sign of [-1,1]){this.rod(driver,[-.05,.35,sign*.075],[-.51,.29,sign*.08],.053,'seat','cockpit');this.rod(driver,[-.51,.29,sign*.08],[-.91,.35,sign*.08],.046,'seat','cockpit')}
 this.applyMaterials();
 }
 makeFloor(old:boolean,ax:number){const g=this.group('floor','floor',[0,-.18,0]),width=old?.83:.755;const height=(x:number,z:number)=>{const q=Math.abs(z),start=old?-1.04:-.83,throat=old?.15:.63;let y;if(x<throat){const t=T.MathUtils.clamp((x-start)/(throat-start),0,1);y=lerp(old?.20:.12,.072,t*t*(3-2*t))}else{const t=(x-throat)/(2.05-throat);y=.072+(old?.245:.20)*t*t}const across=Math.sin(T.MathUtils.clamp((q-.17)/(width-.17),0,1)*Math.PI);return .087+(y-.087)*Math.pow(Math.max(0,across),.75)};
 for(const sign of [-1,1]){this.mesh(g,surface(100,48,(u,v)=>{const x=lerp(old?-1.10:-.87,2.08,u),z=sign*lerp(.15,width,v);return[x,height(x,z),z]},[145,34]),'carbon','tunnels');this.mesh(g,surface(100,8,(u,v)=>{const x=lerp(old?-1.1:-.87,2.06,u),z=sign*(width+v*.032);return[x,.093+.018*Math.sin(u*Math.PI*2)**2,z]},[145,5]),'matte','floor');this.tube(g,[[old?-1.1:-.87,.11,sign*(width+.02)],[-.35,.1,sign*(width+.023)],[.53,.108,sign*(width+.02)],[1.25,.11,sign*(width-.01)],[1.66,.09,sign*(width-.03)]],.005,'red','floor');
 if(!old){this.mesh(g,surface(36,14,(u,v)=>{const x=-.89+u*.47,z=sign*(width-.014-.095*Math.sin(u*Math.PI));return[x,.09+v*(.29*(1-u)+.10),z]},[22,15]),'carbon','floor')}
 const fenceCount=old?4:3;for(let i=0;i<fenceCount;i++){const z=sign*(.22+i*(width-.28)/(fenceCount-1));this.mesh(g,surface(28,1,(u,v)=>{const x=lerp(old?-1.1:-.87,old?-.45:-.25,u),zz=z+sign*.05*(1-u);return[x,lerp(.09,height(x,zz)+.02,v),zz]},[30,4]),'carbon','floor')}
 for(let i=0;i<3;i++){const z=sign*(.23+i*.18);this.mesh(g,surface(26,1,(u,v)=>{const x=lerp(1.1,2.08,u);return[x,lerp(.09,height(x,z),v),z]},[40,9]),'carbon','diffuser')}
 }
 this.box(g,[3.13,.01,.30],[.42,.075,0],'wood','floor',.007);this.box(g,[3.12,.017,.314],[.42,.09,0],'carbon','floor',.01);for(const x of [-.88,-.37,.43,1.20,1.74]){const disc=this.mesh(g,new T.CylinderGeometry(.036,.036,.013,24),'metal','floor',[x,.072,0]);for(const sign of [-1,1])this.mesh(g,new T.CylinderGeometry(.006,.006,.016,8),'metal','floor',[x,.068,sign*.099])}
 const rear=this.group('diffuser','floor',[.25,-.10,0]);this.mesh(rear,surface(25,20,(u,v)=>{const x=1.78+u*.36,z=(v-.5)*1.28;return[x,.10+u*.17*Math.sin(v*Math.PI),z]},[16,50]),'carbon','diffuser');
 }
 makeWheel(front:boolean,sign:number,ax:number,width:number,old:boolean){const x=front?-ax:ax,w=front?(old?.305:.280):(old?.405:.375),r=old?.36:(front?.3525:.355),z=sign*(width-w/2);const assembly=this.group('tyres','wheelAssembly',[front?-.1:.1,.10,sign*.47]);assembly.position.set(0,0,0);const pivot=new T.Group();pivot.position.set(x,r,z);assembly.add(pivot);const wheel=new T.Group();pivot.add(wheel);this.wheelPivots.push({pivot,wheel,side:sign,front,x,z,r});
 const profile=[new T.Vector2(.226,-w*.42),new T.Vector2(.246,-w*.495),new T.Vector2(.285,-w*.51),new T.Vector2(r-.042,-w*.50),new T.Vector2(r-.019,-w*.435),new T.Vector2(r-.004,-w*.32),new T.Vector2(r,-w*.2),new T.Vector2(r,0),new T.Vector2(r,w*.2),new T.Vector2(r-.004,w*.32),new T.Vector2(r-.019,w*.435),new T.Vector2(r-.042,w*.50),new T.Vector2(.285,w*.51),new T.Vector2(.246,w*.495),new T.Vector2(.226,w*.42),new T.Vector2(.226,-w*.42)];const tyre=this.mesh(wheel,new T.LatheGeometry(profile,96),'rubber','tyres');tyre.rotation.x=Math.PI/2;
 const rim=this.cylinder(wheel,.2286,w*.82,[0,0,0],'rim','tyres');const hole=this.cylinder(wheel,.199,w*.85,[0,0,0],'black','tyres');
 for(const side of [-1,1]){this.ring(wheel,.212,.231,[0,0,side*w*.445],'metal','tyres');for(let i=0;i<10;i++){const a=i/10*Math.PI*2;const spoke=this.box(wheel,[.19,.016,.023],[Math.cos(a)*.115,Math.sin(a)*.115,side*w*.432],'rim','tyres',.005);spoke.rotation.z=a}
 const mark=this.mesh(wheel,new T.PlaneGeometry(r*2,r*2),'rubber','tyres',[0,0,side*(w*.507)]);(mark as T.Mesh).material=new T.MeshBasicMaterial({map:(this.markTexture??=tyreMarkings()),transparent:true,depthWrite:false,side:T.DoubleSide,polygonOffset:true,polygonOffsetFactor:-1});mark.userData.baseColor=new T.Color('#ffffff');if(side===-1)mark.rotation.y=Math.PI;
 }
 if(old){const cover=this.cylinder(wheel,.207,.009,[0,0,sign*(w*.451)],'carbon','tyres');for(let i=0;i<16;i++){const a=i/16*Math.PI*2;this.rod(wheel,[.07*Math.cos(a),.07*Math.sin(a),sign*w*.47],[.19*Math.cos(a+.06),.19*Math.sin(a+.06),sign*w*.47],.0025,'rim','tyres')}}
 this.cylinder(pivot,.047,w+.025,[0,0,0],'metal','brakes');this.cylinder(wheel,.046,.018,[0,0,sign*(w*.49)],'metal','tyres');const nut=this.mesh(wheel,new T.CylinderGeometry(.025,.025,.027,6),'metal','tyres',[0,0,sign*(w*.53)]);nut.rotation.x=Math.PI/2;
 // Brake package remains when tyre and rim are removed.
 const rotor=this.mesh(pivot,new T.TorusGeometry(.128,.031,10,72),'disc','brakes',[0,0,-sign*.022]);rotor.scale.z=.5;this.ring(pivot,.070,.160,[0,0,-sign*.004],'disc','brakes');this.ring(pivot,.070,.160,[0,0,-sign*.037],'disc','brakes');const holes=new T.InstancedMesh(new T.CircleGeometry(.0026,6),this.mat.black.clone(),144),vents=new T.InstancedMesh(new T.CylinderGeometry(.0035,.0035,.025,6),this.mat.black.clone(),48),hm=new T.Object3D();let hi=0;for(let i=0;i<48;i++){const a=i/48*Math.PI*2;for(const rad of [.108,.136,.151]){hm.position.set(Math.cos(a+rad)*rad,Math.sin(a+rad)*rad,sign*.001);hm.rotation.set(0,sign<0?Math.PI:0,0);hm.updateMatrix();holes.setMatrixAt(hi++,hm.matrix)}hm.position.set(.156*Math.cos(a),.156*Math.sin(a),-.019);hm.rotation.set(Math.PI/2,0,0);hm.updateMatrix();vents.setMatrixAt(i,hm.matrix)}holes.userData.id=vents.userData.id='brakes';pivot.add(holes,vents);this.meshes.push(holes,vents);
 const cal=this.box(pivot,[.067,.175,.07],[.127,.004,-sign*.015],'caliper','brakes',.025);for(const yy of [-.049,0,.049])this.cylinder(pivot,.012,.008,[.147,yy,sign*.025],'metal','brakes');this.cylinder(pivot,.069,.065,[0,0,-sign*.045],'rim','brakes');this.box(pivot,[.09,.24,.051],[0,0,-sign*.104],'metal','suspension',.025);this.tube(pivot,[[-.09,.04,-sign*.13],[-.13,.10,-sign*.14],[-.17,.15,-sign*.13]],.032,'carbon','brakes');this.box(pivot,[.045,.105,.053],[-.171,.16,-sign*.13],'black','brakes',.017);
 const suspension=this.group('suspension','suspension',[0,.09,sign*.18]);const endZ=z-sign*.085;
 const add=(a:Vec,b:Vec,tie=false)=>{const m=this.rod(suspension,a,b,tie?.008:.012,tie?'metal':'carbon','suspension',tie?1:1.65);this.links.push({mesh:m,a,b,side:sign,tie,front,x,z})};
 for(const level of [0,1]){const yy=level?r+.135:r-.127,inY=front?(level?.47:.18):(level?.44:.18);add([x-.29,inY,sign*.19],[x,yy,endZ]);add([x+.29,inY,sign*.19],[x,yy,endZ])}
 add([x+.20,r-.022,sign*.2],[x+.082,r-.016,endZ],true);add([x+.13,front?.49:.45,sign*.15],[x-.03,r-.11,endZ]);
 if(!front)this.rod(suspension,[x,r,0],[x,r,endZ],.025,'metal','power');else{this.box(suspension,[.06,.038,.13],[x+.12,.49,sign*.17],'metal','suspension',.008);this.rod(suspension,[x+.10,.48,sign*.17],[x+.25,.43,sign*.08],.026,'metal','suspension')}
 }
 makeFlow(){while(this.flowRoot.children.length){const o=this.flowRoot.children[0];this.flowRoot.remove(o);o.traverse(obj=>{if((obj as T.Mesh).geometry)(obj as T.Mesh).geometry.dispose();const m=(obj as T.Mesh).material;if(m&&!Array.isArray(m))m.dispose()})}this.flows=[];const old=this.s.generation==='2025';for(const sign of [-1,1]){for(let j=0;j<6;j++){const z=sign*(.2+j*.115);const pts:Vec[]=[[-3.5,.18+j*.03,z],[-2.7,.19+j*.03,z],[-1.65,.42+j*.06,z+sign*.10],[-.6,.55+j*.055,z+sign*.16],[.5,.55+j*.05,z+sign*.13],[1.4,.48+j*.045,z+sign*.05],[2.1,.62+j*.04,z],[3.6,.92+j*.025,z]];this.flow(pts,false,j*.13)}for(let j=0;j<5;j++){const z=sign*(.22+j*.11);this.flow([[-3.3,.105,z],[-1.45,.11,z],[-.8,old?.145:.09,z],[.20,.057,z],[1.12,.094,z],[1.85,.16,z],[2.3,.28,z],[3.5,.40,z]],true,j*.19)}this.flow([[-3.3,.51,sign*.92],[-2.1,.52,sign*1.09],[-1.5,.50,sign*1.17],[-.5,.40,sign*1.10],[1,.40,sign*1.08],[2,.5,sign*1.12],[3.5,.54,sign*1.15]],false,.3)}this.flow([[-3.2,1.03,0],[-1.6,1.07,0],[-.1,1.20,0],[1.7,1.24,0],[2.4,1.46,0],[3.5,1.6,0]],false,.17)}
 flow(points:Vec[],floor:boolean,phase:number){const curve=new T.CatmullRomCurve3(points.map(V));const g=new T.BufferGeometry().setFromPoints(curve.getPoints(110));const line=new T.Line(g,new T.LineBasicMaterial({color:floor?'#e16b35':'#3298b0',transparent:true,opacity:.23,depthWrite:false}));this.flowRoot.add(line);const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(new Float32Array(14*3),3));const p=new T.Points(geo,new T.PointsMaterial({color:floor?'#ea783a':'#2aa7c2',size:.026,transparent:true,opacity:.9,depthWrite:false,sizeAttenuation:true}));this.flowRoot.add(p);this.flows.push({curve,points:p,line,phase,floor})}
 applyMaterials(){for(const m of this.meshes){if(m instanceof T.InstancedMesh)continue;const mat=m.material as T.MeshStandardMaterial;if(!mat.color)continue;mat.color.copy(m.userData.baseColor);const selected=this.s.selected===m.userData.id;mat.emissive?.set(selected?'#a13a1b':'#000000');if(m.userData.id==='exhaust'&&mat===this.mat.light)mat.emissive?.set('#ff2200');mat.emissiveIntensity=selected?.25:0;let body=false;let p=m.parent;while(p&&p!==this.root){const part=this.parts.find(g=>g.group===p);if(part)body=part.category==='bodywork';p=p.parent}const trans=this.s.mode==='xray'&&body;mat.transparent=trans||mat instanceof T.MeshBasicMaterial&&!!mat.map&&m.geometry instanceof T.PlaneGeometry;mat.opacity=trans?.16:1;mat.depthWrite=!trans;mat.needsUpdate=true;}}
 update(next:Settings){const gen=next.generation!==this.s.generation,materials=next.mode!==this.s.mode||next.selected!==this.s.selected;const lighting=next.lighting!==this.s.lighting,quality=next.quality!==this.s.quality;this.s={...next};if(gen){this.build();this.makeFlow()}else if(materials)this.applyMaterials();if(lighting){const day=next.lighting==='daylight',technical=next.lighting==='technical';this.scene.background=new T.Color(day?'#e8edf0':technical?'#dce3e7':'#e7eaec');(this.scene.fog as T.Fog).color.copy(this.scene.background as T.Color);this.scene.environmentIntensity=technical?.95:day?1.05:.85;this.key.intensity=day?4.7:technical?2.3:4;this.fill.intensity=technical?2.5:1.7;this.rim.intensity=technical?1.5:2.5;this.grid.visible=technical;this.renderer.toneMappingExposure=technical?1.05:1.12;this.key.color.set(day?'#fff0dc':'#fff8ee')}if(quality){const mobile=this.host.clientWidth<700;this.qualityDpr=next.quality==='low'?1:next.quality==='high'?Math.min(2,devicePixelRatio):Math.min(mobile?1.4:1.8,devicePixelRatio);this.renderer.setPixelRatio(this.qualityDpr);this.key.shadow.mapSize.set(next.quality==='low'?1024:2048,next.quality==='low'?1024:2048);this.key.shadow.map?.dispose();this.key.shadow.map=null;this.resizeNow()}}
 resizeNow(){const {clientWidth:w,clientHeight:h}=this.host;if(!w||!h)return;this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
 view(name:string){const ax=this.s.generation==='2025'?1.8:1.7;const views:Record<string,[Vec,Vec]>={'Front three-quarter':[[-6.6,3.25,6.3],[-.08,.34,0]],'Rear three-quarter':[[6.2,2.7,5.4],[.15,.4,0]],'Side':[[0,1.12,9],[0,.39,0]],'Front':[[-8,.90,0],[-.15,.45,0]],'Rear':[[7,.85,0],[.2,.45,0]],'Top':[[0,9,.001],[0,.1,0]],'Underfloor':[[-.8,-6,3.0],[.1,.1,0]],'Cockpit':[[.35,1.12,.45],[-.47,.53,0]],'Front wing':[[-4.3,1.20,1.9],[-ax-.66,.22,0]],'Rear wing':[[3.7,1.62,2.0],[ax+.12,.82,0]],'Suspension':[[-3.1,1.0,2.6],[-ax,.32,.45]],'Brakes':[[-2.64,.69,2.05],[-ax,.35,.77]]};const v=views[name]||views['Front three-quarter'];this.targetCam=V(v[0]);this.targetLook=V(v[1]);if(['Front three-quarter','Rear three-quarter','Side','Top','Underfloor'].includes(name)){const factor=Math.max(1,1.13/this.camera.aspect);this.targetCam.sub(this.targetLook).multiplyScalar(factor).add(this.targetLook)}if(this.reduced){this.camera.position.copy(this.targetCam);this.controls.target.copy(this.targetLook);this.targetCam=this.targetLook=null}}
 onDown=(e:PointerEvent)=>{this.pointerDown=[e.clientX,e.clientY,Date.now()]};
 pick(e:PointerEvent){const r=this.host.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);return this.ray.intersectObjects(this.root.children,true).find(h=>{let p:T.Object3D|null=h.object;while(p){if(!p.visible)return false;p=p.parent}return !!h.object.userData.id})}
 onUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-this.pointerDown[0],e.clientY-this.pointerDown[1])>6)return;const hit=this.pick(e);if(hit?.object.userData.id)this.select(hit.object.userData.id)};
 onMove=(e:PointerEvent)=>{if(e.buttons)return;const hit=this.pick(e);const id=hit?.object.userData.id;this.hover(id&&components[id]?components[id].name:'');this.host.style.cursor=id?'pointer':'grab'};
 onLeave=()=>{this.hover('')};
 onKey=(e:KeyboardEvent)=>{if(e.target!==this.host)return;const angle=.10;const d=this.camera.position.clone().sub(this.controls.target);if(e.key==='ArrowLeft'||e.key==='ArrowRight'){d.applyAxisAngle(new T.Vector3(0,1,0),e.key==='ArrowLeft'?angle:-angle);this.camera.position.copy(this.controls.target).add(d);e.preventDefault()}if(e.key==='+'||e.key==='='||e.key==='-'){this.camera.position.copy(this.controls.target).add(d.multiplyScalar(e.key==='-'?1.12:.88));e.preventDefault()}if(e.key.toLowerCase()==='r')this.view('Front three-quarter')};
 onVisibility=()=>{this.userActive=!document.hidden};
 onLost=(e:Event)=>{e.preventDefault();this.stats('Graphics interrupted — reload to resume')};
 animateGeometry(dt:number){const a=this.reduced?1:1-Math.exp(-dt*7),floorOnly=this.s.mode==='floor',explode=this.s.mode==='explode'?this.s.explode/100:0;for(const p of this.parts){const floor=p.category==='floor';const internal=p.category==='internals';let visible=true;if(floorOnly)visible=floor;else if(p.category==='bodywork')visible=this.s.bodywork;else if(floor)visible=this.s.floor;else if(p.category==='wheelAssembly')visible=true;else if(p.category==='wings')visible=this.s.wings;else if(p.category==='suspension')visible=this.s.suspension;else if(internal)visible=this.s.internals||this.s.mode==='xray'||this.s.mode==='explode';p.group.visible=visible;p.group.position.lerp(p.offset.clone().multiplyScalar(explode),a);if(p.category==='wheelAssembly'&&floorOnly)p.group.visible=false;}
 const rideOffset=(this.s.ride-45)/1000;this.root.rotation.z=this.s.rake*Math.PI/180;const rakeLift=Math.sin(this.root.rotation.z)*(this.s.generation==='2025'?1.8:1.7);this.root.position.y=rideOffset-.023+rakeLift;
 for(const f of this.frontFlaps){const target=this.s.generation==='2026'&&this.s.wingOpen?-.25:0;f.rotation.z=lerp(f.rotation.z,target,a)}for(const f of this.rearFlaps){const target=this.s.wingOpen?-.31:0;f.rotation.z=lerp(f.rotation.z,target,a)}
 const steer=this.s.steer/6*Math.PI/180;this.steering!.rotation.x=lerp(this.steering!.rotation.x,-this.s.steer*Math.PI/180,a);
 for(const w of this.wheelPivots){const travel=w.front?this.s.travel/1000:0;w.pivot.position.y=w.r+travel-rideOffset+.023-rakeLift-Math.sin(this.root.rotation.z)*w.x;const inner=w.side*Math.sign(steer)>0;const yaw=steer*(inner?1.04:.96);w.pivot.rotation.y=lerp(w.pivot.rotation.y,w.front?-yaw:0,a);w.wheel.visible=this.s.wheels&&!(w.front&&w.side===1&&this.s.removeWheel);for(const child of w.pivot.children)if(child!==w.wheel&&child.userData.id==='suspension')child.visible=this.s.suspension;}
 for(const l of this.links){const b=V(l.b);const travel=l.front?this.s.travel/1000:0;b.y+=travel-rideOffset+.023-rakeLift-Math.sin(this.root.rotation.z)*l.x;if(l.front&&l.tie){const local=b.clone().sub(new T.Vector3(l.x,b.y,l.z));local.applyAxisAngle(new T.Vector3(0,1,0),-steer);b.x=l.x+local.x;b.z=l.z+local.z}this.positionRod(l.mesh,V(l.a),b,l.tie?1:1.65)}
 this.ground.visible=this.camera.position.y>.04&&!floorOnly&&!explode;this.shadow.visible=this.ground.visible;this.grid.visible=this.ground.visible&&this.s.lighting==='technical';this.flowRoot.visible=this.s.mode==='aero'||floorOnly;this.flowRoot.position.y=rideOffset-.023;this.flowRoot.rotation.z=this.root.rotation.z;
 }
 loop=()=>{if(this.stopped)return;this.frame=requestAnimationFrame(this.loop);if(!this.userActive)return;const dt=Math.min(this.clock.getDelta(),.04),time=this.clock.elapsedTime;if(this.targetCam&&this.targetLook){const a=1-Math.exp(-dt*6);this.camera.position.lerp(this.targetCam,a);this.controls.target.lerp(this.targetLook,a);if(this.camera.position.distanceTo(this.targetCam)<.003){this.targetCam=null;this.targetLook=null}}this.controls.autoRotate=this.s.spin&&!this.reduced;this.controls.autoRotateSpeed=.45;this.controls.update(dt);this.animateGeometry(dt);if(this.flowRoot.visible){for(const f of this.flows){const only=this.s.mode==='floor';f.points.visible=f.line.visible=!only||f.floor;const pos=f.points.geometry.getAttribute('position');for(let i=0;i<pos.count;i++){const t=(i/pos.count+time*this.s.speed/3200+f.phase)%1;const p=f.curve.getPointAt(t);if(f.floor){p.y+=(this.s.ride-45)/1000*.2;p.y+=Math.max(0,(p.x-1.1))*.03*(this.s.wingOpen?1:0)}pos.setXYZ(i,p.x,p.y,p.z)}pos.needsUpdate=true}}
 this.renderer.render(this.scene,this.camera);this.renderCount++;if(time-this.lastTime>3){const fps=this.renderCount/(time-this.lastTime);this.stats(`${Math.round(fps)} fps · ${Math.round(this.renderer.info.render.triangles/1000)}k triangles`);if(this.s.quality==='auto'&&fps<25&&this.renderer.getPixelRatio()>1){this.renderer.setPixelRatio(Math.max(1,this.renderer.getPixelRatio()-.25));this.resizeNow()}this.renderCount=0;this.lastTime=time}}
 disposeCar(){this.root.traverse(o=>{if((o as T.Mesh).geometry)(o as T.Mesh).geometry.dispose();const m=(o as T.Mesh).material;if(m&&!Array.isArray(m))m.dispose()});this.root.clear();this.parts=[];this.meshes=[];this.materials=[]}
 dispose(){this.stopped=true;cancelAnimationFrame(this.frame);this.resize.disconnect();this.controls.dispose();this.host.removeEventListener('pointerdown',this.onDown);this.host.removeEventListener('pointerup',this.onUp);this.host.removeEventListener('pointermove',this.onMove);this.host.removeEventListener('pointerleave',this.onLeave);this.host.removeEventListener('keydown',this.onKey);document.removeEventListener('visibilitychange',this.onVisibility);this.disposeCar();this.scene.traverse(o=>{if((o as T.Mesh).geometry)(o as T.Mesh).geometry.dispose();const m=(o as T.Mesh).material;if(m&&!Array.isArray(m))m.dispose()});this.environment.dispose();for(const m of Object.values(this.mat)){m.map?.dispose();m.dispose()}this.renderer.dispose();this.renderer.domElement.remove()}
}
